name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run makefile clean, build, then execute
      run: |
        make clean
        make all
        ls
        cd build
        ls
        cd apps
        ls
        ./program
      
