name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run makefile clean
      run: make clean
    - name: Run makefile all and execute main
      run: | 
        make all
        ls
        cd /build/apps/
        ls
        ./program
      
