name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run makefile clean
      run: make clean
    - name: Run makefile all
      run: make all
    - name: run tensor library test executable
      run: |
        cd /build/apps/
        ls
        ./program
        
      
